version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - fpm
    volumes:
      - ./:/var/www/laravel/
  fpm:
    build:
      context: .
      dockerfile: Dockerfile_fpm
    volumes:
      - ./:/var/wwww/laravel
